{
  positions(
    first: 100,
    orderBy: timestamp,
    orderDirection: desc,
    where: {
      isCollateral: true,
      balance_gt: 0,
      market_: {
        inputToken_in: [
          "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",  # WETH
          "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6",  # WBTC  
        ]
      }
    }
  ) {
    id
    market {
      inputToken {
        id
        symbol
      }
    }
    account {
      id
    }
    side
    isCollateral
    balance
  }
}
